const OTP_TTL_SECONDS = 5 * 60;
const OTP_RESEND_WINDOW_SECONDS = 10 * 60;
const OTP_MAX_REQUESTS_PER_WINDOW = 3;
const JWT_EXPIRES_IN = "7d";
const ADMIN_JWT_EXPIRES_IN = "12h";
const KIOSK_JWT_EXPIRES_IN = "30d";
const IMPACT_CACHE_TTL_SECONDS = 24 * 60 * 60;

module.exports = {
  ADMIN_JWT_EXPIRES_IN,
  IMPACT_CACHE_TTL_SECONDS,
  JWT_EXPIRES_IN,
  KIOSK_JWT_EXPIRES_IN,
  OTP_MAX_REQUESTS_PER_WINDOW,
  OTP_RESEND_WINDOW_SECONDS,
  OTP_TTL_SECONDS,
};
