const OTP_TTL_SECONDS = 5 * 60;
const OTP_RESEND_WINDOW_SECONDS = 10 * 60;
const OTP_MAX_REQUESTS_PER_WINDOW = 3;
const JWT_EXPIRES_IN = "7d";

module.exports = {
  JWT_EXPIRES_IN,
  OTP_MAX_REQUESTS_PER_WINDOW,
  OTP_RESEND_WINDOW_SECONDS,
  OTP_TTL_SECONDS,
};
